// Auto-generated by Enigma256Bridge — include at module scope (not inside initial).
localparam int ENIGMA256_N = 36;
localparam [63:0] ENIGMA256_LFSR = 64'he4606d5937150fd4;
localparam [7:0] ENIGMA256_R1 = 8'h5a;
localparam [7:0] ENIGMA256_R2 = 8'h52;
localparam [7:0] ENIGMA256_R3 = 8'hc7;
localparam [7:0] ENIGMA256_R4 = 8'hd1;