// Auto-generated by Enigma256Bridge — include at module scope (not inside initial).
localparam int ENIGMA256_N = 36;
localparam [63:0] ENIGMA256_LFSR = 64'hf96e53eee3a3ea13;
localparam [7:0] ENIGMA256_R1 = 8'h64;
localparam [7:0] ENIGMA256_R2 = 8'hf5;
localparam [7:0] ENIGMA256_R3 = 8'h45;
localparam [7:0] ENIGMA256_R4 = 8'h36;