// Auto-generated by Enigma256Bridge — include at module scope (not inside initial).
localparam int ENIGMA256_N = 36;
localparam [63:0] ENIGMA256_LFSR = 64'h45eef606d2c147a4;
localparam [7:0] ENIGMA256_R1 = 8'h23;
localparam [7:0] ENIGMA256_R2 = 8'h1c;
localparam [7:0] ENIGMA256_R3 = 8'h03;
localparam [7:0] ENIGMA256_R4 = 8'h66;