// Auto-generated by Enigma256Bridge — include at module scope (not inside initial).
// Compatibility: E256/v2/gen0/fa246e9cba9009a4799e5a81722a9b14e9a67293d9621b45985c5f3e620865d4/fixture-v4
// Receipt SHA-256: 5c5bc931a145048037ec420b2c0c47ff310570e963bd45b8262f18a1640f0027
localparam int ENIGMA256_N = 1024;
localparam [63:0] ENIGMA256_LFSR = 64'hfe64c0cbe733b528;
localparam [63:0] ENIGMA256_COUNTER = 64'h0000000000000000;
localparam [7:0] ENIGMA256_R1 = 8'h2f;
localparam [7:0] ENIGMA256_R2 = 8'h82;
localparam [7:0] ENIGMA256_R3 = 8'h81;
localparam [7:0] ENIGMA256_R4 = 8'hb9;