`timescale 1ns / 1ps

module enigma_256_core (
    input  wire        clk,
    input  wire        rst_n,
    
    // Control Interface
    input  wire        load_state,      // Assert to load initial seeds
    input  wire [63:0] init_lfsr,       // 64-bit seed from HKDF
    input  wire [7:0]  init_r1_pos,     // Grundstellung (Starting positions)
    input  wire [7:0]  init_r2_pos,
    input  wire [7:0]  init_r3_pos,
    input  wire [7:0]  init_r4_pos,

    // Data Interface
    input  wire [7:0]  data_in,
    input  wire        valid_in,
    output wire [7:0]  data_out,
    output wire        valid_out
);

    // =========================================================================
    // 1. STATE MEMORY (Look-Up Tables generated by HKDF Day Key)
    // In a real FPGA, these would be synthesized as Block RAMs (BRAM) or 
    // Distributed RAMs loaded during the initialization phase.
    // =========================================================================
    reg [7:0] plugboard  [0:255]; // Involution (A->B means B->A)
    reg [7:0] r1_fwd     [0:255]; reg [7:0] r1_rev [0:255];
    reg [7:0] r2_fwd     [0:255]; reg [7:0] r2_rev [0:255];
    reg [7:0] r3_fwd     [0:255]; reg [7:0] r3_rev [0:255];
    reg [7:0] r4_fwd     [0:255]; reg [7:0] r4_rev [0:255];
    reg [7:0] reflector  [0:255]; // Un-reflector (Permits A->A)

    // =========================================================================
    // 2. THE STEPPING ENGINE (64-bit Galois LFSR)
    // =========================================================================
    reg  [63:0] lfsr;
    wire [63:0] lfsr_next;
    
    // Primitive polynomial for 64-bit Galois LFSR
    // Taps at 64, 63, 61, 60
    assign lfsr_next = {lfsr[62:0], 1'b0} ^ (lfsr[63] ? 64'hD800000000000000 : 64'h0);

    reg [7:0] offset_r1, offset_r2, offset_r3, offset_r4;

    // Use specific LFSR bits as stepping triggers for the 4 active rotors
    wire step_r1 = lfsr[0];
    wire step_r2 = lfsr[15];
    wire step_r3 = lfsr[31];
    wire step_r4 = lfsr[47];

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            lfsr      <= 64'd0;
            offset_r1 <= 8'd0; offset_r2 <= 8'd0; 
            offset_r3 <= 8'd0; offset_r4 <= 8'd0;
        end else if (load_state) begin
            lfsr      <= init_lfsr;
            offset_r1 <= init_r1_pos;
            offset_r2 <= init_r2_pos;
            offset_r3 <= init_r3_pos;
            offset_r4 <= init_r4_pos;
        end else if (valid_in) begin
            // Clock the LFSR and step the rotors simultaneously
            lfsr      <= lfsr_next;
            offset_r1 <= offset_r1 + step_r1;
            offset_r2 <= offset_r2 + step_r2;
            offset_r3 <= offset_r3 + step_r3;
            offset_r4 <= offset_r4 + step_r4;
        end
    end

    // =========================================================================
    // 3. THE CRYPTOGRAPHIC DATAPATH
    // 8-bit overflow naturally handles the modulo 256 math.
    // =========================================================================
    
    // Forward Pass
    wire [7:0] pb_in     = plugboard[data_in];
    
    wire [7:0] r1_in_fwd = pb_in + offset_r1;
    wire [7:0] r1_out_fwd= r1_fwd[r1_in_fwd] - offset_r1;
    
    wire [7:0] r2_in_fwd = r1_out_fwd + offset_r2;
    wire [7:0] r2_out_fwd= r2_fwd[r2_in_fwd] - offset_r2;
    
    wire [7:0] r3_in_fwd = r2_out_fwd + offset_r3;
    wire [7:0] r3_out_fwd= r3_fwd[r3_in_fwd] - offset_r3;
    
    wire [7:0] r4_in_fwd = r3_out_fwd + offset_r4;
    wire [7:0] r4_out_fwd= r4_fwd[r4_in_fwd] - offset_r4;
    
    // The Un-Reflector
    wire [7:0] ref_out   = reflector[r4_out_fwd];
    
    // Reverse Pass
    wire [7:0] r4_in_rev = ref_out + offset_r4;
    wire [7:0] r4_out_rev= r4_rev[r4_in_rev] - offset_r4;
    
    wire [7:0] r3_in_rev = r4_out_rev + offset_r3;
    wire [7:0] r3_out_rev= r3_rev[r3_in_rev] - offset_r3;
    
    wire [7:0] r2_in_rev = r3_out_rev + offset_r2;
    wire [7:0] r2_out_rev= r2_rev[r2_in_rev] - offset_r2;
    
    wire [7:0] r1_in_rev = r2_out_rev + offset_r1;
    wire [7:0] r1_out_rev= r1_rev[r1_in_rev] - offset_r1;
    
    // Final Plugboard Pass (Involution, so we use the same array)
    assign data_out = plugboard[r1_out_rev];
    
    // Delay valid signal by 1 clock to match output if pipelined (combinational here)
    reg valid_q;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) valid_q <= 1'b0;
        else        valid_q <= valid_in;
    end
    assign valid_out = valid_q;

endmodule
