// Auto-generated by Enigma256Bridge — include at module scope (not inside initial).
// Compatibility: E256/v2/gen0/2a9f54c70a1619805a911758158f1e2204b0fd96c35102a9db5f4575aeb40cb0/fixture-v3
// Receipt SHA-256: 5c5bc931a145048037ec420b2c0c47ff310570e963bd45b8262f18a1640f0027
localparam int ENIGMA256_N = 1024;
localparam [63:0] ENIGMA256_LFSR = 64'ha406bb0e7e86e624;
localparam [7:0] ENIGMA256_R1 = 8'hb6;
localparam [7:0] ENIGMA256_R2 = 8'h07;
localparam [7:0] ENIGMA256_R3 = 8'h17;
localparam [7:0] ENIGMA256_R4 = 8'hd1;