// Exhaustive functional check for the E256-H rotor-lane cost model.
//
// Contract: directives/e256-hardware-cost-preregistration.json
// Driven by: Scripts/e256_hardware_cost_gate.py, which writes the parameter
// and expected-vector files from the frozen E256-W model KDF.
//
// Every variant is checked on all 256 inputs. Any mismatch prints FAIL and
// aborts, which makes the runner refuse the canonical receipt.

`default_nettype none
`timescale 1ns / 1ps

module e256h_cost_lanes_tb;

  // Frozen parameters, supplied by the runner as plusargs / include file.
  reg [7:0]    p_in;
  reg [7:0]    p_out;
  reg [63:0]   l_in;
  reg [63:0]   l_out;
  reg [7:0]    c_in;
  reg [7:0]    c_out;
  reg [2047:0] tbl;

  reg [7:0] params_mem    [0:19];
  reg [7:0] expect_fixed  [0:255];
  reg [7:0] expect_offset [0:255];
  reg [7:0] expect_affine [0:255];

  reg [7:0] x;

  wire [7:0] y_identity;
  wire [7:0] y_xor_only;
  wire [7:0] y_fixed;
  wire [7:0] y_offset;
  wire [7:0] y_offset_alt;
  wire [7:0] y_affine;
  wire [7:0] y_table;

  integer checks;
  integer failures;
  integer i;
  integer fd;

  e256h_cost_identity   u_identity   (.x(x), .y(y_identity));
  e256h_cost_xor_only   u_xor_only   (.x(x), .p_in(p_in), .y(y_xor_only));
  e256h_cost_fixed      u_fixed      (.x(x), .y(y_fixed));
  e256h_cost_offset     u_offset     (.x(x), .p_in(p_in), .p_out(p_out),
                                      .y(y_offset));
  e256h_cost_offset_alt u_offset_alt (.x(x), .p_in(p_in), .p_out(p_out),
                                      .y(y_offset_alt));
  e256h_cost_affine     u_affine     (.x(x), .l_in(l_in), .l_out(l_out),
                                      .c_in(c_in), .c_out(c_out),
                                      .y(y_affine));
  e256h_cost_table      u_table      (.x(x), .tbl(tbl), .y(y_table));

  task check(input [127:0] label, input [7:0] got, input [7:0] want);
    begin
      checks = checks + 1;
      if (got !== want) begin
        failures = failures + 1;
        $display("FAIL %0s x=%02h got=%02h want=%02h", label, x, got, want);
      end
    end
  endtask

  initial begin
    checks = 0;
    failures = 0;

    // Parameters and expected vectors are generated by the runner.
    $readmemh("build/e256h-cost/params.hex", params_mem);
    p_in  = params_mem[0];
    p_out = params_mem[1];
    c_in  = params_mem[2];
    c_out = params_mem[3];
    for (i = 0; i < 8; i = i + 1) begin
      l_in[8*i +: 8]  = params_mem[4 + i];
      l_out[8*i +: 8] = params_mem[12 + i];
    end

    $readmemh("build/e256h-cost/expect_fixed.hex", expect_fixed);
    $readmemh("build/e256h-cost/expect_offset.hex", expect_offset);
    $readmemh("build/e256h-cost/expect_affine.hex", expect_affine);
    for (i = 0; i < 256; i = i + 1) begin
      tbl[8*i +: 8] = expect_affine[i];
    end

    for (i = 0; i < 256; i = i + 1) begin
      x = i[7:0];
      #1;
      check("identity",   y_identity,   x);
      check("xor_only",   y_xor_only,   x ^ p_in);
      check("fixed",      y_fixed,      expect_fixed[i]);
      check("offset",     y_offset,     expect_offset[i]);
      check("offset_alt", y_offset_alt, expect_offset[i]);
      check("affine",     y_affine,     expect_affine[i]);
      check("table",      y_table,      expect_affine[i]);
    end

    fd = $fopen("build/e256h-cost/functional.txt", "w");
    $fwrite(fd, "checks %0d\n", checks);
    $fwrite(fd, "failures %0d\n", failures);
    $fclose(fd);

    $display("E256H_COST_TB checks=%0d failures=%0d", checks, failures);
    if (failures == 0) begin
      $display("E256H_COST_TB PASS");
    end else begin
      $display("E256H_COST_TB FAIL");
    end
    $finish;
  end

endmodule

`default_nettype wire
