#!/usr/bin/env bash
# HELUT grand audit — Phase 0.9 M5 push-button reproducibility.
# Default: formal certificates + Sage estimator + short SING (minutes).
# --full: also Metal wavefront SING at N=1024 (C20/C21; tens of minutes).
set -euo pipefail
cd "$(dirname "$0")/.."

FULL=0
NO_TEXTBOOK=0
for arg in "$@"; do
  case "$arg" in
    --full) FULL=1 ;;
    --no-textbook) NO_TEXTBOOK=1 ;;
    -h|--help)
      echo "Usage: $0 [--full] [--no-textbook]"
      echo "  default   formal certs + Sage (C23) + short encrypted SING"
      echo "  --full    also Metal N=1024 boolean/crypto SING (C20/C21)"
      echo "  --no-textbook  skip make textbook + git stamp"
      exit 0
      ;;
  esac
done

mkdir -p logs
STAMP=$(date -u +%Y%m%dT%H%M%SZ)
SHA=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
EPOCH=$(sed -n 's/.*\\livingepoch{\([^}]*\)}.*/\1/p' textbook/preamble.tex | head -1)
EPOCH=${EPOCH:-unknown}
LOG="logs/helut-grand-audit-${STAMP}.log"
BIN_BENCH=".build/release/helut-bench"
BIN_UMBRELLA=".build/release/helut"

{
  echo "=== HELUT grand audit ${STAMP} ==="
  echo "git ${SHA}  livingepoch ${EPOCH}"
  echo ""

  echo "######## Build release binaries ########"
  swift build -c release --product helut-bench
  swift build -c release --product helut
  echo ""

  echo "######## Formal + covering certificates (C19/C24/C25/C27/C29/C31) ########"
  swift test -c release --filter \
    'testTensorLUTFormalCertificate|testTensorLUTFormalCorollaryCertificate|testEnigma256FormalCertificate|testGGSWPublicMSCoveringCertificate|testGGSWIncompleteCoveringCertificate'
  echo ""

  echo "######## Sage lattice-estimator fill-in (C23) ########"
  if [[ ! -f logs/helut-estimator-pending.json ]]; then
    "$BIN_UMBRELLA" --estimator-export > logs/helut-estimator-pending.json 2>/dev/null \
      || "$BIN_BENCH" --estimator-export > logs/helut-estimator-pending.json
  fi
  if ./Scripts/helut_sage_estimate.sh; then
    echo "Sage estimator: OK"
  else
    echo "WARNING: Sage estimator step failed (H1 / environment). Continuing."
  fi
  echo ""

  echo "######## Short encrypted SING (demo N, CPU-only) ########"
  # Metal at N=8 has hit a Trace/BPT trap; default audit stays CPU.
  "$BIN_BENCH" --bench netlist.json --degree 8 --bench-encrypted --cpu-only --sing --vectors 4 \
    --paths 'blind-rotate public-ms boolean'
  echo ""

  if [[ "$FULL" -eq 1 ]]; then
    echo "######## Metal wavefront SING N=1024 (C20 / C21) ########"
    "$BIN_BENCH" --bench netlist.json --degree 1024 --bench-encrypted --sing --vectors 2 \
      --paths 'blind-rotate-metal public-ms boolean'
    echo ""
    "$BIN_BENCH" --bench netlist.json --degree 1024 --bench-encrypted --sing --vectors 2 \
      --paths 'blind-rotate-metal public-ms crypto'
    echo ""
  else
    echo "(skip Metal N=1024 SING — pass --full)"
    echo ""
  fi

  if [[ "$NO_TEXTBOOK" -eq 0 ]]; then
    echo "######## Textbook rebuild + git stamp ########"
    printf '%s\n' \
      '% Auto-generated by Scripts/helut_grand_audit.sh — do not hand-edit.' \
      "\\newcommand{\\gitstamp}{${SHA}}" \
      "\\newcommand{\\auditepoch}{${EPOCH}}" \
      "\\newcommand{\\audittime}{${STAMP}}" \
      > textbook/git-stamp.tex
    if make textbook; then
      echo "Textbook: OK (stamped ${SHA})"
    else
      echo "WARNING: textbook rebuild failed (TeX tools?). Stamp written; PDF pending."
    fi
    echo ""
  fi

  echo "=== GRAND AUDIT DONE ${STAMP} git=${SHA} ==="
} 2>&1 | tee "$LOG"

echo "Wrote $LOG"
