import XCTest
import Metal
@testable import HELUTCore
@testable import HELUTToolKit

/// Production-width conformance for the unified Verilog Mulein Future Bank.
///
/// The fixtures are P1030684 known-key controls only. Expected full receipts are generated by
/// the independent Swift board, which blindly enumerates one-edge reductions. Truth metadata is
/// read afterwards only to select exact positives, fixed wrong-hypothesis probes, and composed
/// indel-plus-garble repairs. This test reads no P1030680 target data and establishes cleartext
/// source/post-Yosys/JSON/TensorLUT parity, not FHE.
final class MuleinFutureTensorLUTTests: XCTestCase {
    private let bankLanes = 1
    private let maxEdges = 40
    private let maxSteps = 80
    private let edgeBits = 6
    private let stepBits = 7
    private let tagBits = 32

    private struct OracleKey: Hashable {
        let settingLane: Int
        let futureIndex: Int
        let seed: Int
    }

    private struct CasePlan {
        let label: String
        let settingLane: Int
        let futureIndex: Int
        let seed: Int
        let tag: UInt32
    }

    private struct GradeCase {
        let label: String
        let settingLane: Int
        let futureIndex: Int
        let packed: MuleinFutureTensorLUTPackedBatch
        let expected: MuleinFutureMetalHit?
    }

    private func toolPath(_ name: String) -> String? {
        for candidate in [
            "/opt/homebrew/bin/\(name)",
            "/usr/local/bin/\(name)",
            "/usr/bin/\(name)"
        ] where FileManager.default.isExecutableFile(atPath: candidate) {
            return candidate
        }
        return nil
    }

    private func repositoryRoot() throws -> URL {
        var url = URL(fileURLWithPath: #filePath)
        for _ in 0..<8 {
            url.deleteLastPathComponent()
            if FileManager.default.fileExists(
                atPath: url.appendingPathComponent("Package.swift").path
            ), FileManager.default.fileExists(
                atPath: url.appendingPathComponent(
                    "Apps/Mulein/rtl/mulein_future_tensorlut_top.sv"
                ).path
            ) {
                return url
            }
        }
        throw NSError(
            domain: "MuleinFutureTensorLUTTests", code: 1,
            userInfo: [NSLocalizedDescriptionKey: "repository root not found"]
        )
    }

    @discardableResult
    private func run(_ executable: String, _ arguments: [String], cwd: URL) throws -> String {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: executable)
        process.arguments = arguments
        process.currentDirectoryURL = cwd
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe
        try process.run()
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        let output = String(decoding: data, as: UTF8.self)
        guard process.terminationStatus == 0 else {
            throw NSError(
                domain: "MuleinFutureTensorLUTTests",
                code: Int(process.terminationStatus),
                userInfo: [NSLocalizedDescriptionKey:
                    "\(executable) \(arguments.joined(separator: " ")) failed:\n"
                        + String(output.suffix(12_000))]
            )
        }
        return output
    }

    private func makeCases() throws -> (MuleinFutureTensorLUTControlFixture, [GradeCase]) {
        let control = try makeMuleinFutureTensorLUTControlFixture()
        XCTAssertEqual(control.work.count, 4)
        XCTAssertEqual(control.labels.count, control.work.count)
        XCTAssertEqual(control.trueSeeds.count, control.work.count)
        XCTAssertEqual(control.envelopeWork.count, 3)
        XCTAssertEqual(control.envelopeLabels.count, control.envelopeWork.count)
        XCTAssertEqual(control.envelopeTrueSeeds.count, control.envelopeWork.count)
        XCTAssertEqual(control.composedWork.count, 4)
        XCTAssertEqual(control.composedLabels.count, control.composedWork.count)
        XCTAssertEqual(control.composedTrueSeeds.count, control.composedWork.count)

        let allWork = control.work + control.envelopeWork + control.composedWork
        XCTAssertEqual(allWork.count, 11)

        // Enumerate both the published setting and its adjacent negative, every Future, and all
        // 26 seeds before reading truth seeds or constructing a submitted hardware job.
        let oracle = try evaluateMuleinFutureSwiftOracle(
            work: allWork,
            bombe: control.bombe,
            settingRange: control.settingLane..<(control.settingLane + 2)
        )
        var oracleByKey: [OracleKey: MuleinFutureMetalHit] = [:]
        for hit in oracle {
            let key = OracleKey(
                settingLane: hit.settingLane,
                futureIndex: hit.futureIndex,
                seed: hit.seed
            )
            if oracleByKey.updateValue(hit, forKey: key) != nil {
                XCTFail("Swift oracle emitted duplicate key \(key)")
            }
        }

        // Truth metadata is used only after blind oracle completion to choose probes.
        let trueLane = control.settingLane
        let adjacentLane = trueLane + 1
        let trueSeeds = control.trueSeeds
        let envelopeTrueSeeds = control.envelopeTrueSeeds
        let composedTrueSeeds = control.composedTrueSeeds
        XCTAssertEqual(envelopeTrueSeeds, [8, 9, 21], "expected I/J/V truth seeds")
        XCTAssertEqual(composedTrueSeeds[0], composedTrueSeeds[1])
        XCTAssertEqual(composedTrueSeeds[2], composedTrueSeeds[3])
        XCTAssertEqual(allWork[4].future.menu.central, 3, "delta-6 central must be D")
        XCTAssertEqual(allWork[5].future.menu.central, 4, "delta-8 central must be E")
        XCTAssertEqual(allWork[6].future.menu.central, 13, "wrong-delta central must be N")

        let delta6Key = OracleKey(settingLane: trueLane, futureIndex: 4, seed: 8)
        let delta8Key = OracleKey(settingLane: trueLane, futureIndex: 5, seed: 9)
        let wrongDeltaKey = OracleKey(settingLane: trueLane, futureIndex: 6, seed: 21)
        let wrongSettingKey = OracleKey(settingLane: adjacentLane, futureIndex: 5, seed: 9)
        let wrongSeedKey = OracleKey(settingLane: trueLane, futureIndex: 5, seed: 10)
        let delta6GarbleExactKey = OracleKey(
            settingLane: trueLane, futureIndex: 7, seed: composedTrueSeeds[0]
        )
        let delta6GarbleRepairKey = OracleKey(
            settingLane: trueLane, futureIndex: 8, seed: composedTrueSeeds[1]
        )
        let delta8GarbleExactKey = OracleKey(
            settingLane: trueLane, futureIndex: 9, seed: composedTrueSeeds[2]
        )
        let delta8GarbleRepairKey = OracleKey(
            settingLane: trueLane, futureIndex: 10, seed: composedTrueSeeds[3]
        )
        let delta6Expected = try XCTUnwrap(
            oracleByKey[delta6Key], "correct delta-6 probe must survive"
        )
        let delta8Expected = try XCTUnwrap(
            oracleByKey[delta8Key], "correct delta-8 probe must survive"
        )
        XCTAssertTrue(delta6Expected.exact)
        XCTAssertEqual(delta6Expected.droppedEdgeMask, 0)
        XCTAssertTrue(delta8Expected.exact)
        XCTAssertEqual(delta8Expected.droppedEdgeMask, 0)
        XCTAssertNil(oracleByKey[wrongDeltaKey], "wrong delta unexpectedly survived as a ghost")
        XCTAssertNil(oracleByKey[wrongSettingKey], "adjacent setting unexpectedly survived")
        XCTAssertNil(oracleByKey[wrongSeedKey], "adjacent seed unexpectedly survived")

        XCTAssertNil(
            oracleByKey[delta6GarbleExactKey],
            "delta-6 plus garble must reject the true candidate at tolerance 0"
        )
        let delta6GarbleRepair = try XCTUnwrap(
            oracleByKey[delta6GarbleRepairKey],
            "delta-6 plus garble must recover the true candidate at tolerance 1"
        )
        XCTAssertNil(
            oracleByKey[delta8GarbleExactKey],
            "delta-8 plus garble must reject the true candidate at tolerance 0"
        )
        let delta8GarbleRepair = try XCTUnwrap(
            oracleByKey[delta8GarbleRepairKey],
            "delta-8 plus garble must recover the true candidate at tolerance 1"
        )
        let garbleEdge = control.envelopeGarbleCribIndex
        let expectedDropMask = UInt64(1) << UInt64(garbleEdge)
        XCTAssertFalse(delta6GarbleRepair.exact)
        XCTAssertEqual(delta6GarbleRepair.droppedEdgeMask, expectedDropMask)
        XCTAssertEqual(
            delta6GarbleRepair.repair.droppedEdgeIDs,
            [allWork[8].future.boardEdges[garbleEdge].id],
            "delta-6 repair dropped the wrong stable edge"
        )
        XCTAssertFalse(delta8GarbleRepair.exact)
        XCTAssertEqual(delta8GarbleRepair.droppedEdgeMask, expectedDropMask)
        XCTAssertEqual(
            delta8GarbleRepair.repair.droppedEdgeIDs,
            [allWork[10].future.boardEdges[garbleEdge].id],
            "delta-8 repair dropped the wrong stable edge"
        )

        var plans = control.work.indices.map { index in
            CasePlan(
                label: control.labels[index],
                settingLane: trueLane,
                futureIndex: index,
                seed: trueSeeds[index],
                tag: UInt32(0x4D55_0000) + UInt32(index)
            )
        }
        plans.append(contentsOf: [
            CasePlan(
                label: control.envelopeLabels[0], settingLane: trueLane,
                futureIndex: 4, seed: envelopeTrueSeeds[0], tag: 0x4D55_0004
            ),
            CasePlan(
                label: control.envelopeLabels[1], settingLane: trueLane,
                futureIndex: 5, seed: envelopeTrueSeeds[1], tag: 0x4D55_0005
            ),
            CasePlan(
                label: control.envelopeLabels[2], settingLane: trueLane,
                futureIndex: 6, seed: envelopeTrueSeeds[2], tag: 0x4D55_0006
            ),
            CasePlan(
                label: "wrong-setting-vyab", settingLane: adjacentLane,
                futureIndex: 5, seed: envelopeTrueSeeds[1], tag: 0x4D55_0007
            ),
            CasePlan(
                label: "wrong-seed-k", settingLane: trueLane,
                futureIndex: 5, seed: 10, tag: 0x4D55_0008
            )
        ])
        plans.append(contentsOf: control.composedWork.indices.map { index in
            CasePlan(
                label: control.composedLabels[index],
                settingLane: trueLane,
                futureIndex: 7 + index,
                seed: composedTrueSeeds[index],
                tag: UInt32(0x4D55_0009) + UInt32(index)
            )
        })

        let cases = try plans.map { plan -> GradeCase in
            let job = MuleinFutureTensorLUTJob(
                work: allWork[plan.futureIndex], seed: plan.seed, tag: plan.tag
            )
            let setting = (
                plan.settingLane / 17_576,
                (plan.settingLane / 676) % 26,
                (plan.settingLane / 26) % 26,
                plan.settingLane % 26
            )
            let packed = try packMuleinFutureTensorLUTBatch(
                jobs: [job],
                bombe: control.bombe,
                setting: setting,
                bankLanes: bankLanes,
                maxEdges: maxEdges,
                maxSteps: maxSteps,
                edgeBits: edgeBits,
                stepBits: stepBits,
                tagBits: tagBits
            )
            let key = OracleKey(
                settingLane: plan.settingLane,
                futureIndex: plan.futureIndex,
                seed: plan.seed
            )
            return GradeCase(
                label: plan.label,
                settingLane: plan.settingLane,
                futureIndex: plan.futureIndex,
                packed: packed,
                expected: oracleByKey[key]
            )
        }

        XCTAssertNotNil(cases[0].expected, "clean known-key seed must survive exactly")
        XCTAssertTrue(cases[0].expected?.exact == true)
        XCTAssertNil(cases[1].expected, "gap+garble must fail without edge repair")
        let repaired = try XCTUnwrap(cases[2].expected)
        XCTAssertFalse(repaired.exact)
        XCTAssertEqual(repaired.repair.droppedEdgeIDs.count, 1)
        XCTAssertEqual(
            repaired.repair.droppedEdgeIDs[0].cribIndex,
            control.postGapGarbleCribIndex,
            "combined indel+garble control repaired the wrong stable edge"
        )
        XCTAssertEqual(control.work[3].future.menu.steps.max(), 79)
        XCTAssertTrue(cases[3].expected?.exact == true)

        XCTAssertEqual(allWork[4].future.geometry.transmittedLength, 78)
        XCTAssertEqual(allWork[4].future.menu.steps, Array(38..<78))
        XCTAssertEqual(allWork[4].future.menu.steps.max(), 77)
        XCTAssertEqual(
            allWork[4].future.boardEdges.map(\.id.recordedIndex),
            Array(32..<72).map(Optional.some)
        )
        XCTAssertEqual(allWork[5].future.geometry.transmittedLength, 80)
        XCTAssertEqual(allWork[5].future.menu.steps, Array(40..<80))
        XCTAssertEqual(allWork[5].future.menu.steps.max(), 79)
        XCTAssertEqual(
            allWork[5].future.boardEdges.map(\.id.recordedIndex),
            Array(32..<72).map(Optional.some)
        )
        XCTAssertTrue(cases[4].expected?.exact == true)
        XCTAssertEqual(cases[4].expected?.droppedEdgeMask, 0)
        XCTAssertTrue(cases[5].expected?.exact == true)
        XCTAssertEqual(cases[5].expected?.droppedEdgeMask, 0)
        XCTAssertNil(cases[6].expected)
        XCTAssertNil(cases[7].expected)
        XCTAssertNil(cases[8].expected)

        XCTAssertEqual(allWork[8].future.geometry.transmittedLength, 78)
        XCTAssertEqual(allWork[8].future.menu.steps.max(), 77)
        XCTAssertEqual(allWork[8].future.menu.steps[garbleEdge], 58)
        XCTAssertEqual(allWork[8].future.boardEdges[garbleEdge].id.recordedIndex, 52)
        XCTAssertEqual(allWork[10].future.geometry.transmittedLength, 80)
        XCTAssertEqual(allWork[10].future.menu.steps.max(), 79)
        XCTAssertEqual(allWork[10].future.menu.steps[garbleEdge], 60)
        XCTAssertEqual(allWork[10].future.boardEdges[garbleEdge].id.recordedIndex, 52)
        XCTAssertNil(cases[9].expected)
        XCTAssertEqual(cases[10].expected, delta6GarbleRepair)
        XCTAssertNil(cases[11].expected)
        XCTAssertEqual(cases[12].expected, delta8GarbleRepair)
        return (control, cases)
    }

    private func integer(_ bits: [UInt8], base: Int = 0, width: Int? = nil) -> UInt64 {
        let count = width ?? max(0, bits.count - base)
        var value: UInt64 = 0
        for bit in 0..<min(count, 64) where base + bit < bits.count && bits[base + bit] != 0 {
            value |= UInt64(1) << UInt64(bit)
        }
        return value
    }

    private func mergedInputs(
        _ packed: MuleinFutureTensorLUTPackedBatch,
        module: YosysModule,
        resetn: Bool,
        start: Bool,
        ready: UInt64 = 0
    ) -> [String: [UInt8]] {
        var result: [String: [UInt8]] = [:]
        for (name, port) in module.ports where port.direction == "input" {
            result[name] = [UInt8](repeating: 0, count: port.bits.count)
        }
        for (name, bits) in packed.portInputs(
            resetn: resetn, start: start, resultReadyMask: ready
        ) {
            result[name] = bits
        }
        return result
    }

    private func assertReceipt(
        _ receipt: MuleinFutureTensorLUTCircuitReceipt,
        gradeCase: GradeCase,
        file: StaticString = #filePath,
        line: UInt = #line
    ) throws {
        let job = gradeCase.packed.jobs[0]
        XCTAssertTrue(receipt.valid, "\(gradeCase.label): result is not held valid", file: file, line: line)
        XCTAssertFalse(receipt.configError, "\(gradeCase.label): config_error", file: file, line: line)
        XCTAssertEqual(receipt.tag, job.tag, "\(gradeCase.label): tag", file: file, line: line)
        XCTAssertEqual(receipt.seed, job.seed, "\(gradeCase.label): seed", file: file, line: line)
        XCTAssertGreaterThan(receipt.cycleCount, 0, file: file, line: line)
        XCTAssertGreaterThan(receipt.closureCount, 0, file: file, line: line)

        guard let expected = gradeCase.expected else {
            XCTAssertFalse(receipt.hit, "\(gradeCase.label): false survivor", file: file, line: line)
            XCTAssertFalse(receipt.exact, file: file, line: line)
            XCTAssertEqual(receipt.droppedEdgeMask, 0, file: file, line: line)
            XCTAssertEqual(receipt.erasedEdge, 63, file: file, line: line)
            XCTAssertEqual(receipt.pairCount, 0, file: file, line: line)
            XCTAssertEqual(receipt.determinedCount, 0, file: file, line: line)
            XCTAssertEqual(receipt.liveHash, 0, file: file, line: line)
            return
        }

        XCTAssertTrue(receipt.hit, "\(gradeCase.label): expected survivor was lost", file: file, line: line)
        XCTAssertEqual(receipt.exact, expected.exact, file: file, line: line)
        XCTAssertEqual(receipt.droppedEdgeMask, expected.droppedEdgeMask, file: file, line: line)
        XCTAssertEqual(receipt.pairCount, expected.pairCount, file: file, line: line)
        XCTAssertEqual(receipt.determinedCount, expected.determinedCount, file: file, line: line)
        XCTAssertEqual(receipt.liveHash, expected.liveHash, file: file, line: line)
        let expectedErased = expected.droppedEdgeMask == 0
            ? (1 << edgeBits) - 1
            : expected.droppedEdgeMask.trailingZeroBitCount
        XCTAssertEqual(receipt.erasedEdge, expectedErased, file: file, line: line)
        XCTAssertEqual(
            try gradeCase.packed.droppedEdgeIDs(for: receipt),
            expected.repair.droppedEdgeIDs,
            "\(gradeCase.label): stable repair provenance",
            file: file,
            line: line
        )
    }

    private func runCleartext(
        moduleName: String,
        module: YosysModule,
        cases: [GradeCase]
    ) throws -> [MuleinFutureTensorLUTCircuitReceipt] {
        try cases.map { gradeCase in
            let simulator = CleartextNetlistSimulator(moduleName: moduleName, module: module)
            simulator.resetState()
            _ = simulator.tick(inputs: mergedInputs(
                gradeCase.packed, module: module, resetn: false, start: false
            ))
            var outputs = simulator.tick(inputs: mergedInputs(
                gradeCase.packed, module: module, resetn: true, start: true
            ))
            var ticks = 0
            while integer(outputs["result_valid"] ?? []) == 0 && ticks < 100_000 {
                outputs = simulator.tick(inputs: mergedInputs(
                    gradeCase.packed, module: module, resetn: true, start: false
                ))
                ticks += 1
            }
            guard integer(outputs["result_valid"] ?? []) == 1 else {
                throw NSError(
                    domain: "MuleinFutureTensorLUTTests", code: 2,
                    userInfo: [NSLocalizedDescriptionKey:
                        "clear simulator timed out on \(gradeCase.label)"]
                )
            }
            let receipt = try gradeCase.packed.decode(outputs: outputs, slot: 0)
            try assertReceipt(receipt, gradeCase: gradeCase)

            // Held-result/backpressure contract: two extra cycles must not alter any field.
            for _ in 0..<2 {
                outputs = simulator.tick(inputs: mergedInputs(
                    gradeCase.packed, module: module, resetn: true, start: false
                ))
                XCTAssertEqual(
                    try gradeCase.packed.decode(outputs: outputs, slot: 0), receipt,
                    "\(gradeCase.label): held receipt changed under backpressure"
                )
            }
            outputs = simulator.tick(inputs: mergedInputs(
                gradeCase.packed, module: module, resetn: true, start: false, ready: 1
            ))
            XCTAssertEqual(integer(outputs["result_valid"] ?? []), 0)
            // CleartextNetlistSimulator, like TensorLUT, returns immediately after DFF update;
            // run one forward/tick phase to settle combinational bank_ready from the new Q state.
            outputs = simulator.tick(inputs: mergedInputs(
                gradeCase.packed, module: module, resetn: true, start: false
            ))
            XCTAssertEqual(integer(outputs["bank_ready"] ?? []), 1)
            return receipt
        }
    }

    private func readPort(
        _ name: String,
        lane: Int,
        module: YosysModule,
        wires: UnsafePointer<Float>,
        totalWires: Int
    ) -> [UInt8] {
        guard let port = module.ports[name] else { return [] }
        return port.bits.map { bit in
            switch bit {
            case .constant(let value): return UInt8(value)
            case .net(let wire): return wires[lane * totalWires + wire] >= 0.5 ? 1 : 0
            }
        }
    }

    private func runTensorLUT(
        device: MTLDevice,
        module: YosysModule,
        netlist: TensorLUTNetlist,
        cases: [GradeCase],
        tickLimit: Int
    ) throws -> [MuleinFutureTensorLUTCircuitReceipt] {
        let batchSize = cases.count
        let pipeline = try TensorLUTPipeline(device: device, netlist: netlist)
        let inits = netlist.packedINITBuffer()
        guard let initsBuffer = device.makeBuffer(
            bytes: inits,
            length: inits.count * MemoryLayout<Float>.stride,
            options: .storageModeShared
        ) else { throw NSError(domain: "MuleinFutureTensorLUTTests", code: 3) }

        var initial = [Float](repeating: 0, count: batchSize * netlist.totalWires)
        netlist.seedConstOne(into: &initial, batchSize: batchSize)
        guard let wireBuffer = device.makeBuffer(
            bytes: initial,
            length: initial.count * MemoryLayout<Float>.stride,
            options: .storageModeShared
        ) else { throw NSError(domain: "MuleinFutureTensorLUTTests", code: 4) }
        let pointer = wireBuffer.contents().bindMemory(
            to: Float.self, capacity: batchSize * netlist.totalWires
        )

        func writeInputs(resetn: Bool, start: Bool, ready: UInt64 = 0) {
            for (lane, gradeCase) in cases.enumerated() {
                let values = mergedInputs(
                    gradeCase.packed, module: module,
                    resetn: resetn, start: start, ready: ready
                )
                for (name, bits) in values {
                    guard let port = module.ports[name] else { continue }
                    for (index, bit) in port.bits.enumerated() {
                        if case .net(let wire) = bit {
                            pointer[lane * netlist.totalWires + wire] = Float(bits[index])
                        }
                    }
                }
            }
        }

        func tick(resetn: Bool, start: Bool, ready: UInt64 = 0) {
            writeInputs(resetn: resetn, start: start, ready: ready)
            pipeline.evaluateTick(
                totalWires: netlist.totalWires,
                initsBuffer: initsBuffer,
                wireBuffer: wireBuffer,
                batchSize: batchSize
            )
        }

        func outputs(lane: Int) -> [String: [UInt8]] {
            var result: [String: [UInt8]] = [:]
            for name in [
                "result_valid", "result_config_error", "result_hit", "result_tags",
                "result_seeds", "result_exact", "result_drop_masks",
                "result_erased_edges", "result_pair_counts", "result_determined_counts",
                "result_live_hashes", "result_cycle_counts", "result_closure_counts",
                "result_drop_trial_counts", "bank_ready"
            ] {
                result[name] = readPort(
                    name, lane: lane, module: module,
                    wires: UnsafePointer(pointer), totalWires: netlist.totalWires
                )
            }
            return result
        }

        tick(resetn: false, start: false)
        tick(resetn: true, start: true)
        var receipts = [MuleinFutureTensorLUTCircuitReceipt?](
            repeating: nil, count: batchSize
        )
        for _ in 0..<tickLimit {
            for lane in cases.indices where receipts[lane] == nil {
                let laneOutputs = outputs(lane: lane)
                if integer(laneOutputs["result_valid"] ?? []) != 0 {
                    let receipt = try cases[lane].packed.decode(
                        outputs: laneOutputs, slot: 0
                    )
                    try assertReceipt(receipt, gradeCase: cases[lane])
                    receipts[lane] = receipt
                }
            }
            if receipts.allSatisfy({ $0 != nil }) { break }
            tick(resetn: true, start: false)
        }
        guard receipts.allSatisfy({ $0 != nil }) else {
            let missing = cases.indices.filter { receipts[$0] == nil }.map { cases[$0].label }
            throw NSError(
                domain: "MuleinFutureTensorLUTTests", code: 5,
                userInfo: [NSLocalizedDescriptionKey: "TensorLUT timed out: \(missing)"]
            )
        }

        // All lanes must remain stable for two complete graph ticks while backpressured.
        for _ in 0..<2 {
            tick(resetn: true, start: false)
            for lane in cases.indices {
                XCTAssertEqual(
                    try cases[lane].packed.decode(outputs: outputs(lane: lane), slot: 0),
                    receipts[lane]!,
                    "\(cases[lane].label): TensorLUT held receipt changed"
                )
            }
        }
        tick(resetn: true, start: false, ready: 1)
        for lane in cases.indices {
            let laneOutputs = outputs(lane: lane)
            XCTAssertEqual(integer(laneOutputs["result_valid"] ?? []), 0)
            // bank_ready is combinational from just-updated Q state and settles next forward pass.
        }
        return receipts.map { $0! }
    }

    private func verilogHex(_ bits: [UInt8]) -> String {
        let digits = "0123456789abcdef"
        let chars = Array(digits)
        var little: [Character] = []
        for nibble in 0..<((bits.count + 3) / 4) {
            var value = 0
            for bit in 0..<4 {
                let index = nibble * 4 + bit
                if index < bits.count && bits[index] != 0 { value |= 1 << bit }
            }
            little.append(chars[value])
        }
        return String(little.reversed())
    }

    private func literal(_ bits: [UInt8]) -> String {
        "\(bits.count)'h\(verilogHex(bits))"
    }

    private func expectedChecks(_ gradeCase: GradeCase) -> String {
        let job = gradeCase.packed.jobs[0]
        let hit = gradeCase.expected != nil
        let exact = gradeCase.expected?.exact ?? false
        let drop = gradeCase.expected?.droppedEdgeMask ?? 0
        let pairs = gradeCase.expected?.pairCount ?? 0
        let determined = gradeCase.expected?.determinedCount ?? 0
        let hash = gradeCase.expected?.liveHash ?? 0
        let erased = drop == 0 ? (1 << edgeBits) - 1 : drop.trailingZeroBitCount
        return """
            check_condition(result_valid === 1'b1, "\(gradeCase.label): result_valid");
            check_condition(result_config_error === 1'b0, "\(gradeCase.label): config_error");
            check_condition(result_hit === 1'b\(hit ? 1 : 0), "\(gradeCase.label): hit");
            check_condition(result_tags === 32'h\(String(job.tag, radix: 16)), "\(gradeCase.label): tag");
            check_condition(result_seeds === 5'd\(job.seed), "\(gradeCase.label): seed");
            check_condition(result_exact === 1'b\(exact ? 1 : 0), "\(gradeCase.label): exact");
            check_condition(result_drop_masks === 40'h\(String(drop, radix: 16)), "\(gradeCase.label): drop mask");
            check_condition(result_erased_edges === 6'd\(erased), "\(gradeCase.label): erased edge");
            check_condition(result_pair_counts === 4'd\(pairs), "\(gradeCase.label): pair count");
            check_condition(result_determined_counts === 5'd\(determined), "\(gradeCase.label): determined count");
            check_condition(result_live_hashes === 32'h\(String(hash, radix: 16)), "\(gradeCase.label): live hash");
            check_condition(result_cycle_counts > 0, "\(gradeCase.label): cycle receipt");
            check_condition(result_closure_counts > 0, "\(gradeCase.label): closure receipt");
        """
    }

    private func sourceTestbench(cases: [GradeCase]) -> String {
        let inputNames = [
            "start_lane_mask", "start_edge_counts", "start_centrals", "start_seeds",
            "start_max_plugs", "start_exact_plugs", "start_tolerances", "start_tags",
            "edge_a_tables", "edge_b_tables", "edge_step_tables", "step_rows"
        ]
        let blocks = cases.enumerated().map { index, gradeCase -> String in
            let assignments = inputNames.map { name in
                let bits = gradeCase.packed.stableInputs[name]!
                return "        \(name) = \(literal(bits));"
            }.joined(separator: "\n")
            let checks = expectedChecks(gradeCase)
            return """
                // Case \(index): \(gradeCase.label)
            \(assignments)
                @(negedge clk); start = 1'b1;
                @(posedge clk); #1;
                check_condition(busy_mask === 1'b1, "\(gradeCase.label): start not accepted");
                @(negedge clk); start = 1'b0;
                wait_cycles = 0;
                while (result_valid !== 1'b1 && wait_cycles < 100000) begin
                    @(posedge clk); #1; wait_cycles = wait_cycles + 1;
                end
            \(checks)
                repeat (2) begin
                    @(posedge clk); #1;
            \(checks)
                end
                $display("RECEIPT case=\(index) label=\(gradeCase.label) hit=%0d exact=%0d drop=%h pairs=%0d determined=%0d hash=%h cycles=%0d closures=%0d trials=%0d",
                    result_hit, result_exact, result_drop_masks, result_pair_counts,
                    result_determined_counts, result_live_hashes, result_cycle_counts,
                    result_closure_counts, result_drop_trial_counts);
                @(negedge clk); result_ready = 1'b1;
                @(posedge clk); #1;
                check_condition(result_valid === 1'b0, "\(gradeCase.label): result not consumed");
                check_condition(bank_ready === 1'b1, "\(gradeCase.label): bank did not rearm");
                @(negedge clk); result_ready = 1'b0;
            """
        }.joined(separator: "\n")

        return """
        `timescale 1ns / 1ps
        module mulein_future_tensorlut_tb;
            localparam BANK_LANES=1, MAX_EDGES=40, MAX_STEPS=80;
            localparam EDGE_BITS=6, STEP_BITS=7, TAG_BITS=32;
            reg clk=0, resetn=0, start=0;
            always #5 clk=~clk;
            reg [0:0] start_lane_mask=0, result_ready=0;
            reg [5:0] start_edge_counts=0;
            reg [4:0] start_centrals=0, start_seeds=0;
            reg [4:0] start_max_plugs=0, start_exact_plugs=0;
            reg [1:0] start_tolerances=0;
            reg [31:0] start_tags=0;
            reg [199:0] edge_a_tables=0, edge_b_tables=0;
            reg [279:0] edge_step_tables=0;
            reg [10399:0] step_rows=0;
            wire bank_ready, bank_complete;
            wire [0:0] active_mask, busy_mask, result_valid, result_config_error;
            wire [0:0] result_hit, result_exact;
            wire [31:0] result_tags;
            wire [4:0] result_seeds;
            wire [39:0] result_drop_masks;
            wire [5:0] result_erased_edges;
            wire [3:0] result_pair_counts;
            wire [4:0] result_determined_counts;
            wire [31:0] result_live_hashes, result_cycle_counts;
            wire [31:0] result_closure_counts, result_drop_trial_counts;

            mulein_future_tensorlut_top dut(.*);
            integer errors=0, wait_cycles=0;
            task automatic check_condition(input condition, input string message);
                begin
                    if (condition !== 1'b1) begin
                        $display("FAIL: %s", message); errors=errors+1;
                    end
                end
            endtask

            initial begin
                repeat (4) @(posedge clk);
                @(negedge clk); resetn=1'b1;
        \(blocks)
                if (errors == 0) begin
                    $display("PASS: production Mulein source/post-Yosys full receipts and backpressure");
                    $finish;
                end
                $fatal(1, "production Mulein testbench recorded %0d errors", errors);
            end
        endmodule
        """
    }

    func testDeltaSixAndEightGarbleSwiftOracleControls() throws {
        let (_, cases) = try makeCases()
        XCTAssertEqual(cases.count, 13)
        XCTAssertEqual(cases[9].label, "delta-6-garble-exact")
        XCTAssertNil(cases[9].expected)
        XCTAssertEqual(cases[10].label, "delta-6-garble-repair")
        XCTAssertNotNil(cases[10].expected)
        XCTAssertEqual(cases[11].label, "delta-8-garble-exact")
        XCTAssertNil(cases[11].expected)
        XCTAssertEqual(cases[12].label, "delta-8-garble-repair")
        XCTAssertNotNil(cases[12].expected)
    }

    func testProductionSourcePostYosysClearAndTensorLUTAgree() throws {
        guard let yosys = toolPath("yosys"),
              let iverilog = toolPath("iverilog"),
              let vvp = toolPath("vvp") else {
            throw XCTSkip("yosys/iverilog/vvp are required for the production Mulein grade")
        }
        guard let device = MTLCreateSystemDefaultDevice() else {
            throw XCTSkip("Metal device is required for the production TensorLUT grade")
        }

        let (_, cases) = try makeCases()
        let root = try repositoryRoot()
        let dir = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("helut-mulein-future-tensorlut-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }

        let seedRTL = root.appendingPathComponent(
            "Apps/Mulein/rtl/mulein_closure_seed.sv"
        ).path
        let topRTL = root.appendingPathComponent(
            "Apps/Mulein/rtl/mulein_future_tensorlut_top.sv"
        ).path
        try sourceTestbench(cases: cases).write(
            to: dir.appendingPathComponent("future_tb.sv"), atomically: true, encoding: .utf8
        )
        let flow = """
        read_verilog -sv \(seedRTL) \(topRTL)
        hierarchy -check -top mulein_future_tensorlut_top
        proc
        flatten
        memory
        opt
        techmap
        opt
        dffunmap
        zinit -all
        abc -lut 6
        opt_clean
        check -assert
        write_json future.json
        write_verilog -noattr future.v
        """
        try flow.write(
            to: dir.appendingPathComponent("flow.ys"), atomically: true, encoding: .utf8
        )

        _ = try run(
            iverilog,
            ["-g2012", "-Wall", "-s", "mulein_future_tensorlut_tb", "-o", "source.vvp",
             seedRTL, topRTL, "future_tb.sv"],
            cwd: dir
        )
        let source = try run(vvp, ["source.vvp"], cwd: dir)
        XCTAssertTrue(source.contains("PASS: production Mulein source/post-Yosys"))
        XCTAssertEqual(source.split(separator: "\n").filter { $0.hasPrefix("RECEIPT ") }.count, cases.count)

        _ = try run(yosys, ["-Q", "-q", "flow.ys"], cwd: dir)
        _ = try run(
            iverilog,
            ["-g2012", "-Wall", "-s", "mulein_future_tensorlut_tb", "-o", "post.vvp",
             "future.v", "future_tb.sv"],
            cwd: dir
        )
        let post = try run(vvp, ["post.vvp"], cwd: dir)
        XCTAssertTrue(post.contains("PASS: production Mulein source/post-Yosys"))
        XCTAssertEqual(
            post.split(separator: "\n").filter { $0.hasPrefix("RECEIPT ") },
            source.split(separator: "\n").filter { $0.hasPrefix("RECEIPT ") },
            "post-Yosys production receipts drifted from source RTL"
        )

        let loaded = loadYosysNetlist(from: dir.appendingPathComponent("future.json").path)
        guard let module = loaded.modules["mulein_future_tensorlut_top"] else {
            return XCTFail("future.json lacks mulein_future_tensorlut_top")
        }
        let executable = module.cells.values.filter { $0.type != "$scopeinfo" }
        let unsupported = Set(executable.map(\.type).filter {
            $0 != "$lut" && $0 != "$_DFF_P_"
        })
        XCTAssertTrue(unsupported.isEmpty, "unsupported production cells: \(unsupported.sorted())")
        XCTAssertTrue(executable.contains { $0.type == "$lut" })
        XCTAssertTrue(executable.contains { $0.type == "$_DFF_P_" })

        let clear = try runCleartext(
            moduleName: "mulein_future_tensorlut_top", module: module, cases: cases
        )
        let tensor = TensorLUTCompiler.compile(module: module)
        XCTAssertEqual(tensor.luts.count, executable.filter { $0.type == "$lut" }.count)
        XCTAssertEqual(tensor.dffs.count, executable.filter { $0.type == "$_DFF_P_" }.count)
        XCTAssertEqual(
            tensor.executionLevels.reduce(0) { $0 + $1.count }, tensor.luts.count
        )
        let limit = max(100, Int(clear.map(\.cycleCount).max() ?? 0) + 16)
        let tensorReceipts = try runTensorLUT(
            device: device, module: module, netlist: tensor, cases: cases, tickLimit: limit
        )
        XCTAssertEqual(tensorReceipts, clear, "TensorLUT production receipts drifted from clear JSON")

        print(
            "MULEIN_FUTURE_TENSORLUT PASS: source == post-Yosys == clear JSON == "
                + "TensorLUT; 40 edges, delta-6 step 77, delta-8 step 79, wrong-delta/setting/seed "
                + "negatives, delta-6/8 plus garble exact negatives and one-edge repairs, "
                + "combined delta-4 indel+garble repair, held receipts; "
                + "\(tensor.luts.count) LUT6, \(tensor.dffs.count) DFF, "
                + "\(tensor.totalWires) wires, \(tensor.executionLevels.count) levels"
        )
        print("MULEIN_FUTURE_TENSORLUT scope: P1030684 cleartext control; not FHE, no P1030680 data")
    }
}
